# Generated by Django 5.2.13 on 2026-05-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('protocol', models.CharField(choices=[('socks5', 'SOCKS5'), ('http', 'HTTP'), ('https', 'HTTPS')], default='socks5', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Виртуальная машина',
                'verbose_name_plural': 'Виртуальные машины',
                'ordering': ['name'],
            },
        ),
    ]
